theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap

# Site settings
title: Bruno Dantas
description: Software Engineering
author: Bruno Dantas
email: your-email@example.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Minima theme settings
minima:
  skin: auto
  social_links:
    github: brunodantas
    linkedin: brunodantasm

# Show excerpts on home page
show_excerpts: true

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_excerpts: true
  - scope:
      path: ""
    values:
      layout: "default"