theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

# Site settings
title: brunodantas
description: >- # this means to ignore newlines until "baseurl:"
  Software engineering and related things.
url: "https://brunodantas.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
github_username: brunodantas
linkedin_username: brunodantasm

# SEO settings
lang: en_US
timezone: America/Sao_Paulo # Change to your timezone
google_analytics: G-6PWGXCY41R # Add your Google Analytics ID here when you get one
google_site_verification: googlec39f095078cc50f8 # Add your Google Search Console verification code

# Social media and Open Graph defaults
social:
  name: brunodantas
  links:
    - https://github.com/brunodantas
    - https://linkedin.com/in/brunodantasm

# Logo for SEO
logo: /assets/images/konario.png # Add a logo if you have one

# Site verification (add these when you get them)
webmaster_verifications:
  google: # Add Google Search Console verification
  bing: # Add Bing Webmaster verification

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Minima theme settings
minima:
  skin: auto
  social_links:
    github: brunodantas
    linkedin: brunodantasm
  google_analytics: G-6PWGXCY41R

# Custom navigation - only show these pages in header
header_pages:
  - blog.md
  - about.md

# Show excerpts on home page
show_excerpts: true

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_excerpts: true
  - scope:
      path: ""
    values:
      layout: "default"
