remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

# Site settings
title: Bruno Dantas
description: Software development blog and personal site
author: Bruno Dantas
email: your-email@example.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Show downloads (set to false for personal site)
show_downloads: false

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"